package lk.aak.agency.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

@Entity
@Table(name = "customers")
public class Customer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Auto-generated by CustomerService when left blank for new customers - not user-required.
    @Size(max = 50, message = "Customer code must be 50 characters or fewer.")
    @Column(name = "customer_code", nullable = false, unique = true)
    private String customerCode;

    @Column(name = "cbl_outlet_id")
    private String cblOutletId;

    @NotBlank(message = "Customer name is required.")
    @Size(max = 150, message = "Customer name must be 150 characters or fewer.")
    @Column(name = "customer_name", nullable = false)
    private String customerName;

    @Column(name = "customer_type")
    private String customerType;

    @Column(columnDefinition = "TEXT")
    private String address;

    private String area;

    @Column(name = "contact_person")
    private String contactPerson;

    @Pattern(regexp = "^$|^[0-9+()\\-\\s]{7,20}$", message = "Enter a valid phone number.")
    private String phone;

    @DecimalMin(value = "0", message = "Credit limit cannot be negative.")
    @Column(name = "credit_limit", precision = 12, scale = 2)
    private BigDecimal creditLimit;

    @Min(value = 0, message = "Payment terms cannot be negative.")
    @Column(name = "payment_terms_days")
    private Integer paymentTermsDays;

    @Column(name = "assigned_employee")
    private String assignedEmployee;

    // FK to employees.id - the source of truth for SALES_REP visibility scoping (see
    // SalesRepScopeService). The legacy assignedEmployee free-text field above is kept only
    // for old data and is no longer written to by the UI.
    @Column(name = "assigned_employee_id")
    private Long assignedEmployeeId;

    private String status;

    @Column(name = "qr_code")
    private String qrCode;

    @Column(columnDefinition = "TEXT")
    private String notes;

    public Customer() {
    }

    @PrePersist
    public void setDefaultValues() {
        if (paymentTermsDays == null) {
            paymentTermsDays = 21;
        }

        if (status == null || status.isBlank()) {
            status = "ACTIVE";
        }

        if (creditLimit == null) {
            creditLimit = BigDecimal.ZERO;
        }
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCustomerCode() {
        return customerCode;
    }

    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    public String getCblOutletId() {
        return cblOutletId;
    }

    public void setCblOutletId(String cblOutletId) {
        this.cblOutletId = cblOutletId;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerType() {
        return customerType;
    }

    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public BigDecimal getCreditLimit() {
        return creditLimit;
    }

    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    public Integer getPaymentTermsDays() {
        return paymentTermsDays;
    }

    public void setPaymentTermsDays(Integer paymentTermsDays) {
        this.paymentTermsDays = paymentTermsDays;
    }

    public String getAssignedEmployee() {
        return assignedEmployee;
    }

    public void setAssignedEmployee(String assignedEmployee) {
        this.assignedEmployee = assignedEmployee;
    }

    public Long getAssignedEmployeeId() {
        return assignedEmployeeId;
    }

    public void setAssignedEmployeeId(Long assignedEmployeeId) {
        this.assignedEmployeeId = assignedEmployeeId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getQrCode() {
        return qrCode;
    }

    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }
}